#!/bin/sh

BRANCH_NAME=$(git rev-parse --abbrev-ref HEAD)

if [ "$BRANCH_NAME" = "main" ]; then
  exit 0
fi

if ! echo "$BRANCH_NAME" | grep -Eq '^(feat|fix|hotfix|docs)/[a-z0-9]+(-[a-z0-9]+)*$'; then
  echo "❌ Nome de branch inválido!"
  echo "👉 Use: tipo/descricao-em-kebab-case"
  echo "👉 Exemplo: feat/notifica-interesse"
  exit 1
fi
