name: Commit Lint

on:
  push:

jobs:
  commitlint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Instalar dependências
        run: npm install

      - name: Validar commits
        run: npx commitlint --from=HEAD~1 --to=HEAD
